server:
  port: 8080

spring:
  liquibase:
    enabled: true
    drop-first: false
    default-schema: public
    change-log: classpath:db/changelog/db.changelog-master.xml

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        show_sql: false
        hbm2ddl:
          auto: none

currency:
  api:
    url: "https://cbr.ru/scripts/XML_daily.asp"
    fallback-url: "https://www.cbr-xml-daily.ru/daily_utf8.xml"

